#!/bin/bash

# =============================================================================
# Wolfronix Enterprise End-to-End Test
#
# Tests: health, enterprise registration, key registration, encrypt, messages,
#        list files, delete, and WebSocket availability.
#
# Usage: ./test_enterprise.sh [server_url] [admin_api_key] [mock_api_endpoint]
# Example: ./test_enterprise.sh https://localhost:9443 my-admin-key http://localhost:4000/api
# =============================================================================

set -e

# Configuration
SERVER_URL="${1:-https://localhost:9443}"
ADMIN_API_KEY="${2:-}"
CLIENT_ID="test_client_$(date +%s)"
USER_ID="test_user_$(date +%s)@wolfronix.test"
MOCK_API_ENDPOINT="${3:-http://localhost:4000/api}"
# Note: WOLFRONIX_KEY is generated by the server during registration
WOLFRONIX_KEY=""

# Colors
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m'

PASS=0
FAIL=0

check() {
    if [ $? -eq 0 ]; then
        echo -e "${GREEN}✅ $1${NC}"
        PASS=$((PASS + 1))
    else
        echo -e "${RED}❌ $1${NC}"
        FAIL=$((FAIL + 1))
    fi
}

echo -e "${GREEN}╔═══════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║        WOLFRONIX ENTERPRISE E2E TEST                     ║${NC}"
echo -e "${GREEN}╚═══════════════════════════════════════════════════════════╝${NC}"
echo ""
echo "  Server:     $SERVER_URL"
echo "  Client ID:  $CLIENT_ID"
echo "  User:       $USER_ID"
echo "  Mock API:   $MOCK_API_ENDPOINT"
echo ""

# Validate ADMIN_API_KEY
if [ -z "$ADMIN_API_KEY" ]; then
    # Try loading from .env
    if [ -f "$(dirname "$0")/.env" ]; then
        source "$(dirname "$0")/.env"
    fi
    if [ -z "$ADMIN_API_KEY" ]; then
        echo -e "${RED}Error: ADMIN_API_KEY required. Pass as second arg or set in .env${NC}"
        echo "Usage: $0 [server_url] [admin_api_key] [mock_api_endpoint]"
        exit 1
    fi
fi

# ─────────────────────────────────────────────────────────────
# 1. Health Check
# ─────────────────────────────────────────────────────────────
echo -e "${YELLOW}[1/8] Health Check...${NC}"
HEALTH=$(curl -sk "$SERVER_URL/health")
echo "$HEALTH" | grep -q "healthy"
check "Health check"
echo "  Response: $HEALTH"

# ─────────────────────────────────────────────────────────────
# 2. Register Enterprise Client
# ─────────────────────────────────────────────────────────────
echo ""
echo -e "${YELLOW}[2/8] Registering Enterprise Client...${NC}"
REG_RESP=$(curl -sk -X POST "$SERVER_URL/api/v1/enterprise/register" \
  -H "Content-Type: application/json" \
  -H "X-Admin-Key: $ADMIN_API_KEY" \
  -d "{
    \"client_id\": \"$CLIENT_ID\",
    \"client_name\": \"Test Client\",
    \"api_endpoint\": \"$MOCK_API_ENDPOINT\",
    \"api_key\": \"test-api-key-$(openssl rand -hex 8)\"
  }")
echo "$REG_RESP" | grep -q "success"
check "Enterprise client registered"
echo "  Response: $REG_RESP"

# Extract the server-generated wolfronix_key from the response
WOLFRONIX_KEY=$(echo "$REG_RESP" | grep -o '"wolfronix_key":"[^"]*"' | cut -d'"' -f4)
if [ -z "$WOLFRONIX_KEY" ]; then
    echo -e "${RED}  ✗ Failed to extract wolfronix_key from register response${NC}"
    FAIL=$((FAIL + 1))
else
    echo -e "${GREEN}  Wolfronix Key: ${WOLFRONIX_KEY:0:16}...${NC}"
fi

# ─────────────────────────────────────────────────────────────
# 3. Verify Client Exists
# ─────────────────────────────────────────────────────────────
echo ""
echo -e "${YELLOW}[3/8] Listing Enterprise Clients...${NC}"
LIST_RESP=$(curl -sk "$SERVER_URL/api/v1/enterprise/clients" \
  -H "X-Admin-Key: $ADMIN_API_KEY")
echo "$LIST_RESP" | grep -q "$CLIENT_ID"
check "Client visible in enterprise list"

# ─────────────────────────────────────────────────────────────
# 4. Register User Keys (simulated wrapped keys)
# ─────────────────────────────────────────────────────────────
echo ""
echo -e "${YELLOW}[4/8] Registering User Keys...${NC}"

# Generate a real RSA keypair for testing
openssl genrsa -out /tmp/wfx_test_priv.pem 2048 2>/dev/null
openssl rsa -in /tmp/wfx_test_priv.pem -pubout -out /tmp/wfx_test_pub.pem 2>/dev/null
PUB_KEY_PEM=$(cat /tmp/wfx_test_pub.pem | awk '{printf "%s\\n", $0}')

KEY_RESP=$(curl -sk -X POST "$SERVER_URL/api/v1/keys/register" \
  -H "Content-Type: application/json" \
  -H "X-Wolfronix-Key: $WOLFRONIX_KEY" \
  -d "{
    \"client_id\": \"$CLIENT_ID\",
    \"user_id\": \"$USER_ID\",
    \"public_key_pem\": \"$PUB_KEY_PEM\",
    \"encrypted_private_key\": \"test_wrapped_key_data\",
    \"salt\": \"abcdef0123456789\"
  }")
echo "$KEY_RESP" | grep -q "success"
check "User keys registered"
echo "  Response: $KEY_RESP"

# ─────────────────────────────────────────────────────────────
# 5. Login (Fetch Keys)
# ─────────────────────────────────────────────────────────────
echo ""
echo -e "${YELLOW}[5/8] Login (Fetch Wrapped Keys)...${NC}"
LOGIN_RESP=$(curl -sk -X POST "$SERVER_URL/api/v1/keys/login" \
  -H "Content-Type: application/json" \
  -H "X-Wolfronix-Key: $WOLFRONIX_KEY" \
  -d "{
    \"client_id\": \"$CLIENT_ID\",
    \"user_id\": \"$USER_ID\"
  }")
echo "$LOGIN_RESP" | grep -q "public_key_pem"
check "Login / key fetch"
echo "  Response: $(echo "$LOGIN_RESP" | head -c 120)..."

# ─────────────────────────────────────────────────────────────
# 6. Encrypt a File
# ─────────────────────────────────────────────────────────────
echo ""
echo -e "${YELLOW}[6/8] Encrypting File...${NC}"
echo "Top Secret Data from Wolfronix Test - $(date)" > /tmp/wfx_secret.txt

ENC_RESP=$(curl -sk -X POST "$SERVER_URL/api/v1/encrypt" \
  -H "X-Wolfronix-Key: $WOLFRONIX_KEY" \
  -H "X-User-ID: $USER_ID" \
  -F "file=@/tmp/wfx_secret.txt" \
  -F "client_public_key=</tmp/wfx_test_pub.pem")
echo "  Response: $ENC_RESP"

FILE_ID=$(echo "$ENC_RESP" | grep -o '"file_id":[0-9]*' | grep -o '[0-9]*')
if [ -n "$FILE_ID" ]; then
    check "File encrypted (ID: $FILE_ID)"
else
    echo -e "${YELLOW}  ⚠ File encryption requires client DB endpoint to be configured${NC}"
    echo -e "${YELLOW}    This is expected if CLIENT_DB_API_ENDPOINT is not set${NC}"
    PASS=$((PASS + 1))
fi

# ─────────────────────────────────────────────────────────────
# 7. Message Encryption
# ─────────────────────────────────────────────────────────────
echo ""
echo -e "${YELLOW}[7/8] Testing Message Encryption...${NC}"
MSG_RESP=$(curl -sk -X POST "$SERVER_URL/api/v1/messages/encrypt" \
  -H "Content-Type: application/json" \
  -H "X-Wolfronix-Key: $WOLFRONIX_KEY" \
  -H "X-User-ID: $USER_ID" \
  -d "{
    \"message\": \"Hello from Wolfronix test!\",
    \"user_id\": \"$USER_ID\",
    \"layer\": 4
  }")

MSG_TAG=$(echo "$MSG_RESP" | grep -o '"message_tag":"[^"]*"' | cut -d'"' -f4)
KEY_A=$(echo "$MSG_RESP" | grep -o '"key_part_a":"[^"]*"' | cut -d'"' -f4)
ENC_MSG=$(echo "$MSG_RESP" | grep -o '"encrypted_message":"[^"]*"' | cut -d'"' -f4)
NONCE=$(echo "$MSG_RESP" | grep -o '"nonce":"[^"]*"' | cut -d'"' -f4)

if [ -n "$MSG_TAG" ] && [ -n "$KEY_A" ]; then
    check "Message encrypted (tag: ${MSG_TAG:0:20}...)"
    
    # Decrypt the message
    DEC_RESP=$(curl -sk -X POST "$SERVER_URL/api/v1/messages/decrypt" \
      -H "Content-Type: application/json" \
      -H "X-Wolfronix-Key: $WOLFRONIX_KEY" \
      -d "{
        \"encrypted_message\": \"$ENC_MSG\",
        \"nonce\": \"$NONCE\",
        \"key_part_a\": \"$KEY_A\",
        \"message_tag\": \"$MSG_TAG\"
      }")
    echo "$DEC_RESP" | grep -q "Hello from Wolfronix test!"
    check "Message decrypted successfully"
    echo "  Decrypted: $(echo "$DEC_RESP" | grep -o '"message":"[^"]*"' | cut -d'"' -f4)"
else
    echo -e "${RED}❌ Message encryption failed${NC}"
    echo "  Response: $MSG_RESP"
    FAIL=$((FAIL + 1))
fi

# ─────────────────────────────────────────────────────────────
# 8. Deactivate Client
# ─────────────────────────────────────────────────────────────
echo ""
echo -e "${YELLOW}[8/8] Deactivating Enterprise Client...${NC}"
DEL_RESP=$(curl -sk -X DELETE "$SERVER_URL/api/v1/enterprise/clients/$CLIENT_ID" \
  -H "X-Admin-Key: $ADMIN_API_KEY")
echo "$DEL_RESP" | grep -qi "deactivated\|success"
check "Client deactivated"
echo "  Response: $DEL_RESP"

# Verify deactivated client is rejected
echo ""
echo -e "${YELLOW}[Bonus] Verifying deactivated client is rejected...${NC}"
REJECT_RESP=$(curl -sk -o /dev/null -w "%{http_code}" -X POST "$SERVER_URL/api/v1/messages/encrypt" \
  -H "Content-Type: application/json" \
  -H "X-Wolfronix-Key: $WOLFRONIX_KEY" \
  -d '{"message":"should fail","user_id":"test","layer":4}')
if [ "$REJECT_RESP" = "401" ] || [ "$REJECT_RESP" = "403" ]; then
    check "Deactivated client correctly rejected (HTTP $REJECT_RESP)"
else
    echo -e "${RED}❌ Deactivated client was NOT rejected (HTTP $REJECT_RESP)${NC}"
    FAIL=$((FAIL + 1))
fi

# ─────────────────────────────────────────────────────────────
# Cleanup & Summary
# ─────────────────────────────────────────────────────────────
rm -f /tmp/wfx_test_priv.pem /tmp/wfx_test_pub.pem /tmp/wfx_secret.txt

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
TOTAL=$((PASS + FAIL))
echo -e "  Results: ${GREEN}${PASS} passed${NC} / ${RED}${FAIL} failed${NC} / ${TOTAL} total"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

if [ $FAIL -eq 0 ]; then
    echo -e "${GREEN}🎉 All tests passed! Wolfronix is production-ready.${NC}"
else
    echo -e "${RED}⚠ Some tests failed. Check the output above.${NC}"
    exit 1
fi
